// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protobuf.proto

package io.mike.protobuf.msg;

public final class Protobuf {
  private Protobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MultipleMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string msg = 1;
    java.util.List<String> getMsgList();
    int getMsgCount();
    String getMsg(int index);
  }
  public static final class MultipleMessage extends
      com.google.protobuf.GeneratedMessage
      implements MultipleMessageOrBuilder {
    // Use MultipleMessage.newBuilder() to construct.
    private MultipleMessage(Builder builder) {
      super(builder);
    }
    private MultipleMessage(boolean noInit) {}
    
    private static final MultipleMessage defaultInstance;
    public static MultipleMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public MultipleMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_MultipleMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_MultipleMessage_fieldAccessorTable;
    }
    
    // repeated string msg = 1;
    public static final int MSG_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList msg_;
    public java.util.List<String>
        getMsgList() {
      return msg_;
    }
    public int getMsgCount() {
      return msg_.size();
    }
    public String getMsg(int index) {
      return msg_.get(index);
    }
    
    private void initFields() {
      msg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < msg_.size(); i++) {
        output.writeBytes(1, msg_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < msg_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(msg_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getMsgList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static io.mike.protobuf.msg.Protobuf.MultipleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.MultipleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.MultipleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.MultipleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.MultipleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.MultipleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.MultipleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static io.mike.protobuf.msg.Protobuf.MultipleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static io.mike.protobuf.msg.Protobuf.MultipleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.MultipleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.mike.protobuf.msg.Protobuf.MultipleMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.mike.protobuf.msg.Protobuf.MultipleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_MultipleMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_MultipleMessage_fieldAccessorTable;
      }
      
      // Construct using io.mike.protobuf.msg.Protobuf.MultipleMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.mike.protobuf.msg.Protobuf.MultipleMessage.getDescriptor();
      }
      
      public io.mike.protobuf.msg.Protobuf.MultipleMessage getDefaultInstanceForType() {
        return io.mike.protobuf.msg.Protobuf.MultipleMessage.getDefaultInstance();
      }
      
      public io.mike.protobuf.msg.Protobuf.MultipleMessage build() {
        io.mike.protobuf.msg.Protobuf.MultipleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private io.mike.protobuf.msg.Protobuf.MultipleMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        io.mike.protobuf.msg.Protobuf.MultipleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public io.mike.protobuf.msg.Protobuf.MultipleMessage buildPartial() {
        io.mike.protobuf.msg.Protobuf.MultipleMessage result = new io.mike.protobuf.msg.Protobuf.MultipleMessage(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          msg_ = new com.google.protobuf.UnmodifiableLazyStringList(
              msg_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.msg_ = msg_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.mike.protobuf.msg.Protobuf.MultipleMessage) {
          return mergeFrom((io.mike.protobuf.msg.Protobuf.MultipleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(io.mike.protobuf.msg.Protobuf.MultipleMessage other) {
        if (other == io.mike.protobuf.msg.Protobuf.MultipleMessage.getDefaultInstance()) return this;
        if (!other.msg_.isEmpty()) {
          if (msg_.isEmpty()) {
            msg_ = other.msg_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMsgIsMutable();
            msg_.addAll(other.msg_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureMsgIsMutable();
              msg_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string msg = 1;
      private com.google.protobuf.LazyStringList msg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMsgIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          msg_ = new com.google.protobuf.LazyStringArrayList(msg_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getMsgList() {
        return java.util.Collections.unmodifiableList(msg_);
      }
      public int getMsgCount() {
        return msg_.size();
      }
      public String getMsg(int index) {
        return msg_.get(index);
      }
      public Builder setMsg(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMsgIsMutable();
        msg_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addMsg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMsgIsMutable();
        msg_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllMsg(
          java.lang.Iterable<String> values) {
        ensureMsgIsMutable();
        super.addAll(values, msg_);
        onChanged();
        return this;
      }
      public Builder clearMsg() {
        msg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addMsg(com.google.protobuf.ByteString value) {
        ensureMsgIsMutable();
        msg_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:io.mike.protobuf.msg.MultipleMessage)
    }
    
    static {
      defaultInstance = new MultipleMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:io.mike.protobuf.msg.MultipleMessage)
  }
  
  public interface TextConfigOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string requiredStr = 2;
    boolean hasRequiredStr();
    String getRequiredStr();
    
    // optional int32 id = 1;
    boolean hasId();
    int getId();
  }
  public static final class TextConfig extends
      com.google.protobuf.GeneratedMessage
      implements TextConfigOrBuilder {
    // Use TextConfig.newBuilder() to construct.
    private TextConfig(Builder builder) {
      super(builder);
    }
    private TextConfig(boolean noInit) {}
    
    private static final TextConfig defaultInstance;
    public static TextConfig getDefaultInstance() {
      return defaultInstance;
    }
    
    public TextConfig getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_TextConfig_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_TextConfig_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string requiredStr = 2;
    public static final int REQUIREDSTR_FIELD_NUMBER = 2;
    private java.lang.Object requiredStr_;
    public boolean hasRequiredStr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getRequiredStr() {
      java.lang.Object ref = requiredStr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          requiredStr_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRequiredStrBytes() {
      java.lang.Object ref = requiredStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        requiredStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getId() {
      return id_;
    }
    
    private void initFields() {
      requiredStr_ = "";
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRequiredStr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getRequiredStrBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getRequiredStrBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static io.mike.protobuf.msg.Protobuf.TextConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.TextConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.TextConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.TextConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.TextConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.TextConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.TextConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static io.mike.protobuf.msg.Protobuf.TextConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static io.mike.protobuf.msg.Protobuf.TextConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.TextConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.mike.protobuf.msg.Protobuf.TextConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.mike.protobuf.msg.Protobuf.TextConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_TextConfig_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_TextConfig_fieldAccessorTable;
      }
      
      // Construct using io.mike.protobuf.msg.Protobuf.TextConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        requiredStr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.mike.protobuf.msg.Protobuf.TextConfig.getDescriptor();
      }
      
      public io.mike.protobuf.msg.Protobuf.TextConfig getDefaultInstanceForType() {
        return io.mike.protobuf.msg.Protobuf.TextConfig.getDefaultInstance();
      }
      
      public io.mike.protobuf.msg.Protobuf.TextConfig build() {
        io.mike.protobuf.msg.Protobuf.TextConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private io.mike.protobuf.msg.Protobuf.TextConfig buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        io.mike.protobuf.msg.Protobuf.TextConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public io.mike.protobuf.msg.Protobuf.TextConfig buildPartial() {
        io.mike.protobuf.msg.Protobuf.TextConfig result = new io.mike.protobuf.msg.Protobuf.TextConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requiredStr_ = requiredStr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.mike.protobuf.msg.Protobuf.TextConfig) {
          return mergeFrom((io.mike.protobuf.msg.Protobuf.TextConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(io.mike.protobuf.msg.Protobuf.TextConfig other) {
        if (other == io.mike.protobuf.msg.Protobuf.TextConfig.getDefaultInstance()) return this;
        if (other.hasRequiredStr()) {
          setRequiredStr(other.getRequiredStr());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRequiredStr()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              requiredStr_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string requiredStr = 2;
      private java.lang.Object requiredStr_ = "";
      public boolean hasRequiredStr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getRequiredStr() {
        java.lang.Object ref = requiredStr_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          requiredStr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRequiredStr(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requiredStr_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequiredStr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requiredStr_ = getDefaultInstance().getRequiredStr();
        onChanged();
        return this;
      }
      void setRequiredStr(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        requiredStr_ = value;
        onChanged();
      }
      
      // optional int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:io.mike.protobuf.msg.TextConfig)
    }
    
    static {
      defaultInstance = new TextConfig(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:io.mike.protobuf.msg.TextConfig)
  }
  
  public interface ResultExtendOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string extendStr = 1;
    boolean hasExtendStr();
    String getExtendStr();
  }
  public static final class ResultExtend extends
      com.google.protobuf.GeneratedMessage
      implements ResultExtendOrBuilder {
    // Use ResultExtend.newBuilder() to construct.
    private ResultExtend(Builder builder) {
      super(builder);
    }
    private ResultExtend(boolean noInit) {}
    
    private static final ResultExtend defaultInstance;
    public static ResultExtend getDefaultInstance() {
      return defaultInstance;
    }
    
    public ResultExtend getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_ResultExtend_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_ResultExtend_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string extendStr = 1;
    public static final int EXTENDSTR_FIELD_NUMBER = 1;
    private java.lang.Object extendStr_;
    public boolean hasExtendStr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getExtendStr() {
      java.lang.Object ref = extendStr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          extendStr_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getExtendStrBytes() {
      java.lang.Object ref = extendStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        extendStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      extendStr_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasExtendStr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getExtendStrBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getExtendStrBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static io.mike.protobuf.msg.Protobuf.ResultExtend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.ResultExtend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.ResultExtend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.ResultExtend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.ResultExtend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.ResultExtend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.ResultExtend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static io.mike.protobuf.msg.Protobuf.ResultExtend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static io.mike.protobuf.msg.Protobuf.ResultExtend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.ResultExtend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.mike.protobuf.msg.Protobuf.ResultExtend prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.mike.protobuf.msg.Protobuf.ResultExtendOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_ResultExtend_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_ResultExtend_fieldAccessorTable;
      }
      
      // Construct using io.mike.protobuf.msg.Protobuf.ResultExtend.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        extendStr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.mike.protobuf.msg.Protobuf.ResultExtend.getDescriptor();
      }
      
      public io.mike.protobuf.msg.Protobuf.ResultExtend getDefaultInstanceForType() {
        return io.mike.protobuf.msg.Protobuf.ResultExtend.getDefaultInstance();
      }
      
      public io.mike.protobuf.msg.Protobuf.ResultExtend build() {
        io.mike.protobuf.msg.Protobuf.ResultExtend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private io.mike.protobuf.msg.Protobuf.ResultExtend buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        io.mike.protobuf.msg.Protobuf.ResultExtend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public io.mike.protobuf.msg.Protobuf.ResultExtend buildPartial() {
        io.mike.protobuf.msg.Protobuf.ResultExtend result = new io.mike.protobuf.msg.Protobuf.ResultExtend(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.extendStr_ = extendStr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.mike.protobuf.msg.Protobuf.ResultExtend) {
          return mergeFrom((io.mike.protobuf.msg.Protobuf.ResultExtend)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(io.mike.protobuf.msg.Protobuf.ResultExtend other) {
        if (other == io.mike.protobuf.msg.Protobuf.ResultExtend.getDefaultInstance()) return this;
        if (other.hasExtendStr()) {
          setExtendStr(other.getExtendStr());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasExtendStr()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              extendStr_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string extendStr = 1;
      private java.lang.Object extendStr_ = "";
      public boolean hasExtendStr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getExtendStr() {
        java.lang.Object ref = extendStr_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          extendStr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setExtendStr(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        extendStr_ = value;
        onChanged();
        return this;
      }
      public Builder clearExtendStr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        extendStr_ = getDefaultInstance().getExtendStr();
        onChanged();
        return this;
      }
      void setExtendStr(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        extendStr_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:io.mike.protobuf.msg.ResultExtend)
    }
    
    static {
      defaultInstance = new ResultExtend(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:io.mike.protobuf.msg.ResultExtend)
  }
  
  public interface ResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 code = 1;
    boolean hasCode();
    int getCode();
    
    // required string message = 2;
    boolean hasMessage();
    String getMessage();
    
    // required .io.mike.protobuf.msg.ResultExtend extend = 3;
    boolean hasExtend();
    io.mike.protobuf.msg.Protobuf.ResultExtend getExtend();
    io.mike.protobuf.msg.Protobuf.ResultExtendOrBuilder getExtendOrBuilder();
  }
  public static final class Result extends
      com.google.protobuf.GeneratedMessage
      implements ResultOrBuilder {
    // Use Result.newBuilder() to construct.
    private Result(Builder builder) {
      super(builder);
    }
    private Result(boolean noInit) {}
    
    private static final Result defaultInstance;
    public static Result getDefaultInstance() {
      return defaultInstance;
    }
    
    public Result getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_Result_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_Result_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCode() {
      return code_;
    }
    
    // required string message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          message_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .io.mike.protobuf.msg.ResultExtend extend = 3;
    public static final int EXTEND_FIELD_NUMBER = 3;
    private io.mike.protobuf.msg.Protobuf.ResultExtend extend_;
    public boolean hasExtend() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public io.mike.protobuf.msg.Protobuf.ResultExtend getExtend() {
      return extend_;
    }
    public io.mike.protobuf.msg.Protobuf.ResultExtendOrBuilder getExtendOrBuilder() {
      return extend_;
    }
    
    private void initFields() {
      code_ = 0;
      message_ = "";
      extend_ = io.mike.protobuf.msg.Protobuf.ResultExtend.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExtend()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getExtend().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMessageBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, extend_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, extend_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static io.mike.protobuf.msg.Protobuf.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static io.mike.protobuf.msg.Protobuf.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static io.mike.protobuf.msg.Protobuf.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static io.mike.protobuf.msg.Protobuf.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.mike.protobuf.msg.Protobuf.Result prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements io.mike.protobuf.msg.Protobuf.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_Result_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.mike.protobuf.msg.Protobuf.internal_static_io_mike_protobuf_msg_Result_fieldAccessorTable;
      }
      
      // Construct using io.mike.protobuf.msg.Protobuf.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getExtendFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (extendBuilder_ == null) {
          extend_ = io.mike.protobuf.msg.Protobuf.ResultExtend.getDefaultInstance();
        } else {
          extendBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.mike.protobuf.msg.Protobuf.Result.getDescriptor();
      }
      
      public io.mike.protobuf.msg.Protobuf.Result getDefaultInstanceForType() {
        return io.mike.protobuf.msg.Protobuf.Result.getDefaultInstance();
      }
      
      public io.mike.protobuf.msg.Protobuf.Result build() {
        io.mike.protobuf.msg.Protobuf.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private io.mike.protobuf.msg.Protobuf.Result buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        io.mike.protobuf.msg.Protobuf.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public io.mike.protobuf.msg.Protobuf.Result buildPartial() {
        io.mike.protobuf.msg.Protobuf.Result result = new io.mike.protobuf.msg.Protobuf.Result(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (extendBuilder_ == null) {
          result.extend_ = extend_;
        } else {
          result.extend_ = extendBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.mike.protobuf.msg.Protobuf.Result) {
          return mergeFrom((io.mike.protobuf.msg.Protobuf.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(io.mike.protobuf.msg.Protobuf.Result other) {
        if (other == io.mike.protobuf.msg.Protobuf.Result.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (other.hasExtend()) {
          mergeExtend(other.getExtend());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        if (!hasMessage()) {
          
          return false;
        }
        if (!hasExtend()) {
          
          return false;
        }
        if (!getExtend().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              message_ = input.readBytes();
              break;
            }
            case 26: {
              io.mike.protobuf.msg.Protobuf.ResultExtend.Builder subBuilder = io.mike.protobuf.msg.Protobuf.ResultExtend.newBuilder();
              if (hasExtend()) {
                subBuilder.mergeFrom(getExtend());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setExtend(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 code = 1;
      private int code_ ;
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getCode() {
        return code_;
      }
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }
      
      // required string message = 2;
      private java.lang.Object message_ = "";
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      void setMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
      }
      
      // required .io.mike.protobuf.msg.ResultExtend extend = 3;
      private io.mike.protobuf.msg.Protobuf.ResultExtend extend_ = io.mike.protobuf.msg.Protobuf.ResultExtend.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          io.mike.protobuf.msg.Protobuf.ResultExtend, io.mike.protobuf.msg.Protobuf.ResultExtend.Builder, io.mike.protobuf.msg.Protobuf.ResultExtendOrBuilder> extendBuilder_;
      public boolean hasExtend() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public io.mike.protobuf.msg.Protobuf.ResultExtend getExtend() {
        if (extendBuilder_ == null) {
          return extend_;
        } else {
          return extendBuilder_.getMessage();
        }
      }
      public Builder setExtend(io.mike.protobuf.msg.Protobuf.ResultExtend value) {
        if (extendBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          extend_ = value;
          onChanged();
        } else {
          extendBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setExtend(
          io.mike.protobuf.msg.Protobuf.ResultExtend.Builder builderForValue) {
        if (extendBuilder_ == null) {
          extend_ = builderForValue.build();
          onChanged();
        } else {
          extendBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeExtend(io.mike.protobuf.msg.Protobuf.ResultExtend value) {
        if (extendBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              extend_ != io.mike.protobuf.msg.Protobuf.ResultExtend.getDefaultInstance()) {
            extend_ =
              io.mike.protobuf.msg.Protobuf.ResultExtend.newBuilder(extend_).mergeFrom(value).buildPartial();
          } else {
            extend_ = value;
          }
          onChanged();
        } else {
          extendBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearExtend() {
        if (extendBuilder_ == null) {
          extend_ = io.mike.protobuf.msg.Protobuf.ResultExtend.getDefaultInstance();
          onChanged();
        } else {
          extendBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public io.mike.protobuf.msg.Protobuf.ResultExtend.Builder getExtendBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getExtendFieldBuilder().getBuilder();
      }
      public io.mike.protobuf.msg.Protobuf.ResultExtendOrBuilder getExtendOrBuilder() {
        if (extendBuilder_ != null) {
          return extendBuilder_.getMessageOrBuilder();
        } else {
          return extend_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          io.mike.protobuf.msg.Protobuf.ResultExtend, io.mike.protobuf.msg.Protobuf.ResultExtend.Builder, io.mike.protobuf.msg.Protobuf.ResultExtendOrBuilder> 
          getExtendFieldBuilder() {
        if (extendBuilder_ == null) {
          extendBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              io.mike.protobuf.msg.Protobuf.ResultExtend, io.mike.protobuf.msg.Protobuf.ResultExtend.Builder, io.mike.protobuf.msg.Protobuf.ResultExtendOrBuilder>(
                  extend_,
                  getParentForChildren(),
                  isClean());
          extend_ = null;
        }
        return extendBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:io.mike.protobuf.msg.Result)
    }
    
    static {
      defaultInstance = new Result(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:io.mike.protobuf.msg.Result)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_io_mike_protobuf_msg_MultipleMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_mike_protobuf_msg_MultipleMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_io_mike_protobuf_msg_TextConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_mike_protobuf_msg_TextConfig_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_io_mike_protobuf_msg_ResultExtend_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_mike_protobuf_msg_ResultExtend_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_io_mike_protobuf_msg_Result_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_mike_protobuf_msg_Result_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Protobuf.proto\022\024io.mike.protobuf.msg\"\036" +
      "\n\017MultipleMessage\022\013\n\003msg\030\001 \003(\t\"-\n\nTextCo" +
      "nfig\022\023\n\013requiredStr\030\002 \002(\t\022\n\n\002id\030\001 \001(\005\"!\n" +
      "\014ResultExtend\022\021\n\textendStr\030\001 \002(\t\"[\n\006Resu" +
      "lt\022\014\n\004code\030\001 \002(\005\022\017\n\007message\030\002 \002(\t\0222\n\006ext" +
      "end\030\003 \002(\0132\".io.mike.protobuf.msg.ResultE" +
      "xtendB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_io_mike_protobuf_msg_MultipleMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_io_mike_protobuf_msg_MultipleMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_io_mike_protobuf_msg_MultipleMessage_descriptor,
              new java.lang.String[] { "Msg", },
              io.mike.protobuf.msg.Protobuf.MultipleMessage.class,
              io.mike.protobuf.msg.Protobuf.MultipleMessage.Builder.class);
          internal_static_io_mike_protobuf_msg_TextConfig_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_io_mike_protobuf_msg_TextConfig_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_io_mike_protobuf_msg_TextConfig_descriptor,
              new java.lang.String[] { "RequiredStr", "Id", },
              io.mike.protobuf.msg.Protobuf.TextConfig.class,
              io.mike.protobuf.msg.Protobuf.TextConfig.Builder.class);
          internal_static_io_mike_protobuf_msg_ResultExtend_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_io_mike_protobuf_msg_ResultExtend_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_io_mike_protobuf_msg_ResultExtend_descriptor,
              new java.lang.String[] { "ExtendStr", },
              io.mike.protobuf.msg.Protobuf.ResultExtend.class,
              io.mike.protobuf.msg.Protobuf.ResultExtend.Builder.class);
          internal_static_io_mike_protobuf_msg_Result_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_io_mike_protobuf_msg_Result_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_io_mike_protobuf_msg_Result_descriptor,
              new java.lang.String[] { "Code", "Message", "Extend", },
              io.mike.protobuf.msg.Protobuf.Result.class,
              io.mike.protobuf.msg.Protobuf.Result.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
